# Generated by Django 5.1.2 on 2024-10-23 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_storeitem_delete_storeitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=200)),
                ('desc', models.TextField(default='', max_length=500)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
