# Generated by Django 5.1.2 on 2024-11-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cart_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
